version: 1.0.0.{build}.{branch}

nuget:
  account_feed: true
  
init:
  - git config --global core.autocrlf true
  
install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json

before_build:
 - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
 - cmd: dnvm install 1.0.0-rc1-final
 - cmd: dnvm upgrade
 - cmd: dnvm update-self
 - cmd: dnvm list
 - cmd: dnvm use 1.0.0-rc1-final
 - cmd: dnu restore AllReadyApp
 - nuget restore AllReadyApp\AllReady.Models\AllReady.Models.csproj -SolutionDirectory .\AllReadyApp
 - nuget restore AllReadyApp\NotificationsProcessor\NotificationsProcessor.csproj -SolutionDirectory .\AllReadyApp

build_script:
 - ps: (Get-Content AllReadyApp\Web-App\AllReady\version.json).replace("GITVERSION", (git rev-parse HEAD)) | Set-Content AllReadyApp\Web-App\AllReady\version.json
 - cmd: msbuild AllReadyApp\AllReady.Models\AllReady.Models.csproj
 - cmd: dnu build AllReadyApp/wrap/AllReady.Models/project.json
 - cmd: dnu build AllReadyApp\Web-App\AllReady\project.json
 - cmd: dnu build AllReadyApp\Web-App\AllReady.UnitTest\project.json
 - cmd: msbuild AllReadyApp\NotificationsProcessor\NotificationsProcessor.csproj

test_script:
 - ps: cd .\AllReadyApp\Web-App\AllReady.UnitTest
 - cmd: dnx test 
 - ps: cd ..\AllReady
 - cmd: dnx web --server.urls http://localhost:33310
 - cmd: ..\..\AllReady.IntegrationTests\bin\Debug\AllReady.IntegrationTests.exe